config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]  


  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'dashboard/index'
  get 'self_destroy', to: 'users#destroy', as: 'self_destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord  
  has_secure_password

  validates_uniqueness_of :email, :message => :user_exist

  validates_presence_of :full_name
  validates_presence_of :email
  validates_presence_of :avatar_image
  validates_presence_of :role
  validates_presence_of :password
  validates_presence_of :password_confirmation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user  
    def current_user
        if session[:user_id]
            @current_user ||= User.find(session[:user_id])
        else
            @current_user = nil
        end
    end

    def authorize
        if current_user.nil?
            redirect_to root_url
        end
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authorize

  def index
    if current_user.role.eql? "Admin"
      @users = User.all
    else
      redirect_to user_path(current_user.id)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to dashboard_index_path, notice: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authorize, except: [:new, :create]

  # GET /users
  # GET /users.json
  def index
    if current_user.role.eql? "Admin"
      @users = User.all
    else
      redirect_to user_path(current_user.id)
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user}
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user}
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy

    redirect_to logout_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:full_name, :email, :avatar_image, :role, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/form_helper.rb
module FormHelper
    def errors_for(form, field)
        content_tag(:p, form.object.errors[field].try(:first), class: 'help-block')
    end

    def form_group_for(form, field, opts={}, &block)
        label = opts.fetch(:label) { true }
        has_errors = form.object.errors[field].present?

        content_tag :div, class: "form-group #{'has-error' if has_errors}" do
            concat form.label(field, class: 'control-label') if label
            concat capture(&block)
            concat errors_for(form, field)
        end
    end
end      

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
<div class="dashboard-workspace">
    <h1>Dashboard!</h1>
    <span class="info">Basic overview for admins.</span>

    <div class="row offset-md-1">
        <div class="info-block col-md-3">
            <svg class="icon" viewBox="0 0 8 8">
                <use class="person" xlink:href="/assets/open-iconic.min.svg#person"></use>
            </svg>
            <div class="info-text">
                <%= User.all.count %><br>
            </div>
            <span class="info">Users total</span>
        </div>
        <div class="info-block col-md-3">
            <svg class="icon" viewBox="0 0 8 8">
                <use class="star" xlink:href="/assets/open-iconic.min.svg#star">
                </use>
            </svg>
            <div class="info-text">
                <%= User.where(:role => "admin").count %><br>
            </div>
            <span class="info">Admins</span>
        </div>
        <div class="info-block col-md-3">
            <svg class="icon" viewBox="0 0 8 8">
                <use class="plus" xlink:href="/assets/open-iconic.min.svg#plus">
                </use>
            </svg>
            <div class="info-text">
                <%= User.where(:role => "no-admin").count %><br>
            </div>
            <span class="info">No-admins</span>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>RubyExercise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <% if current_user %>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href=<%= dashboard_index_path %>>Dashboard <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href=<%= users_path %>>Users <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <%= current_user.email %>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href=<%= logout_path %>>Logout</a>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>

        <%= yield %>
    </div>

    <% else %>
    <%= yield %>
    <% end %>

</body>

</html>

app/views/users/_form.html.erb
<div class="user-form-workspace">
    <div class="col-md-10">
        <%= form_with(model: user, local: true) do |form| %>

        <div class="form-group offset-md-2">
            <label>Full name</label>
            <%= form.text_field :full_name, class: "form-control" %>
        </div>

        <div class="form-group offset-md-2">
            <label>E-mail</label>
            <%= form.text_field :email, class: "form-control" %>
        </div>

        <div class="form-group offset-md-2">
            <label>Avatar image</label>
            <%= form.text_field :avatar_image, class: "form-control" %>
        </div>

        <% if current_user %>
        <% if current_user.role.eql? "Admin" %>

        <div class="form-group offset-md-2">
            <label>Role</label>
            <%= form.select :role, ["Admin", "No-admin"], {}, class: "form-control"%>
        </div>

        <% end %>
        <% else %>

        <input type="hidden" name="user[role]" value="No-admin" />

        <% end %>

        <div class="form-group offset-md-2">
            <label>Password</label>
            <%= form.password_field :password, class: "form-control" %>
        </div>

        <div class="form-group offset-md-2">
            <label>Password confirmation</label>
            <%= form.password_field :password_confirmation, class: "form-control" %>
        </div>

        <div class="actions offset-md-2">
            <%= form.submit 'Submit', class: "btn btn-primary col-md-2" %>
            <a href=<%= users_path %> class="btn btn-success col-md-2">Back</a>
        </div>
    </div>
</div>
<% end %>

app/views/users/edit.html.erb
<%= render 'form', user: @user %>

app/views/users/index.html.erb
<div class="users-workspace">
    <p class="row">
        <a href=<%= new_user_path%> class="btn btn-primary">New User</a>
    </p>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Full name</th>
                <th scope="col">Email</th>
                <th scope="col">Role</th>
                <th scope="col" colspan="3"></th>
            </tr>
        </thead>

        <tbody>
            <% @users.each do |user| %>
            <tr>
                <td scope="row"><%= user.full_name %></td>
                <td scope="row"><%= user.email %></td>
                <td scope="row"><%= user.role %></td>
                <td scope="row"><%= link_to 'Show', user %></td>
                <td scope="row"><%= link_to 'Edit', edit_user_path(user) %></td>
                <td scope="row"><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>
<br>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<div class="users-workspace">
    <div class="h2">
        <%= @user.full_name %>
    </div>
    <br>
    <div class="h5">
        Email:
        <div class="text-muted">
            <%= @user.email %>
        </div>
    </div>
    <br>
    <div class="h5">
        <img src=<%= @user.avatar_image %> alt="User image" class="img-thumbnail user-image">
    </div>

    <div class="h5">
        Role:
        <div class="text-muted">
            <%= @user.role %>
        </div>
    </div>
    <br><br>

    <a href=<%= edit_user_path(@user) %> class="btn btn-primary col-md-1">Edit</a>&nbsp
    <a href=<%= users_path %> class="btn btn-success col-md-1">Back</a>
    <a href=<%= self_destroy_path(:id => current_user.id) %> class="btn btn-danger col-md-1">Delete</a>

</div>